### ISSUE TITLE
Breaks karma testing with phantomjs

### ISSUE THREAD

**Issue by patrickhousley** [web-animations/web-animations-js#106]
Below is the error received when running karma with phantomjs:

```
04 02 2017 23:00:40.353:INFO [karma]: Karma v1.4.1 server started at http://0.0.0.0:9876/
04 02 2017 23:00:40.355:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
04 02 2017 23:00:40.359:INFO [launcher]: Starting browser PhantomJS
04 02 2017 23:00:40.997:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket -cO0ACHZ7ins7g78AAAA with id 58034973
PhantomJS 2.1.1 (Mac OS X 0.0.0) LOG: 'Attempting to configure 'style' with descriptor '{"enumerable":true,"configurable":true}' on object '[object HTMLHtmlElement]' and got error, giving up: TypeError: Attempting to configurable attribute of unconfigurable property.'
PhantomJS 2.1.1 (Mac OS X 0.0.0) LOG: 'Attempting to configure 'style' with descriptor '{"enumerable":true,"configurable":true}' on object '[object HTMLHtmlElement]' and got error, giving up: TypeError: Attempting to configurable attribute of unconfigurable property.'
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'b.style._set(a.propertyName(c),d)')
  at webpack:///~/web-animations-js/web-animations.min.js:15:0 <- src/polyfills.ts:3498
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'b.style._set(a.propertyName(c),d)')
  at webpack:///~/web-animations-js/web-animations.min.js:15:0 <- src/polyfills.ts:3498
```

**Comment by alancutter** [comment]
Can you provide the Karma config & versions you're using?

**Comment by Maistho** [comment]
I've constructed a repo that reproduces the issue.

https://github.com/Maistho/karma-web-animations-phantomjs

My versions are:

- karma@1.2.0
- karma-phantomjs-launcher@1.0.2
- web-animations-js@2.2.2
- phantomjs-prebuilt@2.1.14

Karma config:

```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-phantomjs-launcher'),
      require('karma-remap-istanbul'),
      require('@angular/cli/plugins/karma')
    ],
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['@angular/cli']
    },
    mime: {
      'text/x-typescript': ['ts','tsx']
    },
    remapIstanbulReporter: {
      reports: {
        html: 'coverage',
        lcovonly: './coverage/coverage.lcov'
      }
    },
    angularCli: {
      config: './angular-cli.json',
      environment: 'dev'
    },
    reporters: config.angularCli && config.angularCli.codeCoverage
              ? ['progress', 'karma-remap-istanbul']
              : ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['PhantomJS'],
    singleRun: false
  });
};
```

**Comment by xaralis** [comment]
Any updates on this? It also breaks all sites using some kind of prerendering (like prerender.io) ... flooding our bug reporting site with unrelevant errors :( Would really appreciate at least some work around.

**Comment by josephliccini** [comment]
We use Selenium + PhantomJS and are getting hit by this once we upgraded to Angular 4.0.0...

Any update at all on this? Or perhaps a workaround?

**Comment by mponizil** [comment]
Pinning `web-animations-js` to `2.1.5` appears to get around this issue for me.

**Comment by mscu** [comment]
I pretty much had the same issue as described her when i updated angular cli to 1.0.0 and angular to 4.0.1 today.

This is the solution i came up with, which seems to work so i wanted to briefly how i managed to solve it.

I created a new project with angular cli and saw that the polyfill.ts template has changed:

```typescript
/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
// import 'core-js/es6/symbol';
// import 'core-js/es6/object';
// import 'core-js/es6/function';
// import 'core-js/es6/parse-int';
// import 'core-js/es6/parse-float';
// import 'core-js/es6/number';
// import 'core-js/es6/math';
// import 'core-js/es6/string';
// import 'core-js/es6/date';
// import 'core-js/es6/array';
// import 'core-js/es6/regexp';
// import 'core-js/es6/map';
// import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.


/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';


/** ALL Firefox browsers require the following to support `@angular/animation`. **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
// import 'intl';  // Run `npm install --save intl`.

```

as you can see there is a new entry for web-animations which i uncommented (as well as most of the other polyfills):

```typescript
/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.

/** IE10 and IE11 requires the following to support `@angular/animation`. */
import 'web-animations-js';  // Run `npm install --save web-animations-js`.


/** Evergreen browsers require these. **/
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';


/** ALL Firefox browsers require the following to support `@angular/animation`. **/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.



/***************************************************************************************************
 * Zone JS is required by Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
import 'intl';  // Run `npm install --save intl`.

```

Afterwards i removed the web-animations from my script section in .angular-cli.json

Then all my tests ran already, besides the one where the component actually uses animations.
To solve this, i import the NoopAnimationsModule and it works :)


```typescript
import { TestBed, async } from '@angular/core/testing';

import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { animationPlayerFactory } from './animation-player.factory';

import { AppComponent } from './app.component';

describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      import: [
        NoopAnimationsModule
      ],
      declarations: [
        AppComponent
      ],
    }).compileComponents();
  }));

  // tests...

});

```

This pretty much solved the problem. Now for me it would be interesting if this also works for you and if you think thus is a "proper" solution.

Thanks and best regards,
Matthias

**Comment by geo242** [comment]
@mponizil downgrading to 2.1.5 works for me too

**Comment by Kozlo** [comment]
I had a similar problem. Initially I tried to import BrowserAnimationsModule per the suggestion (in the app I also had to import this for the animations to work), but in PhantomJS the test still didn't work until I replaced BrowserAnimationsModule with NoopAnimationsModule.
